### ISSUE TITLE
[Feature request] Config trigger: Disabling means removal

### ISSUE THREAD

**Issue by mileswest07** [Terrails/Ingotter-1.11.2#1]
Using JEI, I am able to determine that even with ores disabled on the config file, they are still loaded on the mod and still available on JEI with matching recipes, even though their worldgen options are null. Requesting that disabling of an ore from the Ingotter-Generation.cfg will successfully remove all recipes of that ore from game. 

Additionally, this should apply to wires, plates, and dusts, also, as configurable on the Ingotter.cfg file. If disabled, then they shouldn't appear in JEI ( as a Test case).

**Comment by Terrails** [comment]
1. I cannot disable items/blocks from other mods
2. I can disable recipes for the ore but only in furnace and crafting recipes not in recipes for macerator, pulverizer etc.
