### ISSUE TITLE
[Feature request] Config option: Disable nuggets

### ISSUE THREAD

**Issue by mileswest07** [Terrails/Ingotter-1.11.2#2]
Requesting an option that enables/disables a nugget form for each ore. May be implemented in the Ingotter.cfg file as a global setting, or in Ingotter-Generation.cfg as as inline property per ore type.
Test case: placing a single Electrum Ingot on a crafting table does not make the result of 9 Electrum nuggets available.

**Comment by Terrails** [comment]
I cannot disable nugget form of each ore because I cannot disable item/blocks from other mods and I cannot just predict what is the name of the nugget

**Comment by mileswest07** [comment]
If you use the OreDictionary, then this would be a trivial issue to implement. Using the `nugget` prefix would cover all of your needs.

https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/

**Comment by Terrails** [comment]
the problem is to I can't disable items/blocks from other mods, I could if I got the item but I can only disable its recipes

**Comment by mileswest07** [comment]
Um, that's what the OreDictionary is for. Just make sure that any modders who use your mod, know to use the OreDictionary for adding new ores. That way ANY `nugget-*` gets treatment.

**Comment by Terrails** [comment]
I know what OreDictionary is but even if I got the item I still can't do the thing what you wanted, I can only disable all furnace and crafting recipes not custom recipes for that item
